# /boot
IgnorePath /boot/\*

# /etc
IgnorePath /etc/.pwd.lock
IgnorePath /etc/.updated
IgnorePath /etc/adjtime
IgnorePath /etc/audisp
IgnorePath /etc/audit/\*
IgnorePath /etc/ca-certificates/\*
IgnorePath /etc/fonts/conf.d/\*
IgnorePath /etc/group
IgnorePath /etc/group-
IgnorePath /etc/gshadow
IgnorePath /etc/gshadow-
IgnorePath /etc/kernel/pcr\*
IgnorePath /etc/ld.so.cache
IgnorePath /etc/ly/save.txt
IgnorePath /etc/NetworkManager/\*
IgnorePath /etc/os-release
IgnorePath /etc/pacman.d/gnupg/\*
IgnorePath /etc/pacman.d/mirrorlist\*
IgnorePath /etc/passwd
IgnorePath /etc/passwd-
IgnorePath /etc/passwd.OLD
IgnorePath /etc/resolv.conf
IgnorePath /etc/shadow
IgnorePath /etc/shadow-
IgnorePath /etc/shells
IgnorePath /etc/ssh/ssh_host_\*
IgnorePath /etc/ssl/certs/\*
IgnorePath /etc/subgid
IgnorePath /etc/subgid-
IgnorePath /etc/subuid
IgnorePath /etc/subuid-
IgnorePath /etc/texmf/\*
IgnorePath /etc/userdb
IgnorePath /etc/xml/catalog

# /usr
IgnorePath /usr/bin/groupmems
IgnorePath /usr/lib/\*
IgnorePath /usr/lib/locale/locale-archive
IgnorePath /usr/lib/modules/\*
IgnorePath /usr/lib/systemd/\*
IgnorePath /usr/lib/udev/hwdb.bin
IgnorePath /usr/lib32/gconv/\*
IgnorePath /usr/share/applications/mimeinfo.cache
IgnorePath /usr/share/glib-2.0/\*
IgnorePath /usr/share/icons/\*/\*.cache
IgnorePath /usr/share/info/dir
IgnorePath /usr/share/mime/\*
IgnorePath /usr/share/texmf-dist/\*
IgnorePath /usr/share/texmf/ls-R/\*
IgnorePath /usr/share/vim/vimfiles/doc/tags

# /var
IgnorePath /var/.updated
IgnorePath /var/db/\*
IgnorePath /var/lib/archbuild/\*
IgnorePath /var/lib/bluetooth/\*
IgnorePath /var/lib/boltd/\*
IgnorePath /var/lib/btrfs/\*
IgnorePath /var/lib/chrony\*
IgnorePath /var/lib/cni/\*
IgnorePath /var/lib/colord/\*
IgnorePath /var/lib/containers/\*
IgnorePath /var/lib/dbus/machine-id /etc/machine-id
IgnorePath /var/lib/dkms/\*
IgnorePath /var/lib/flatpak/\*
IgnorePath /var/lib/fwupd/\*
IgnorePath /var/lib/lastlog
IgnorePath /var/lib/libuuid
IgnorePath /var/lib/machines
IgnorePath /var/lib/NetworkManager/\*
IgnorePath /var/lib/pacman/\*
IgnorePath /var/lib/passim/\*
IgnorePath /var/lib/plocate/plocate.db
IgnorePath /var/lib/portables
IgnorePath /var/lib/private
IgnorePath /var/lib/rpm/\*
IgnorePath /var/lib/sbctl/\*
IgnorePath /var/lib/systemd/\*
IgnorePath /var/lib/texmf/\*
IgnorePath /var/lib/tlp/rfkill_saved
IgnorePath /var/lib/tpm2-tss
IgnorePath /var/lib/upower/\*
IgnorePath /var/log/\*
IgnorePath /var/tmp/\*