# Temporary fix
# see: https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/work_items/312
BINARIES=(/usr/lib/systemd/systemd-tpm2-setup)
FILES=(/usr/lib/systemd/system/systemd-tpm2-setup-early.service /usr/lib/systemd/system/sysinit.target.wants/systemd-tpm2-setup-early.service)

